<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Seguridad</RootNamespace>
    <AssemblyName>Seguridad</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BE\BE.csproj" />
  </ItemGroup>
</Project>
