<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DAL</RootNamespace>
    <AssemblyName>DAL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\BE\BE.csproj" />
  </ItemGroup>
</Project>
