<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>BLL</RootNamespace>
    <AssemblyName>BLL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\BE\BE.csproj" />
    <ProjectReference Include="..\Servicios\Servicios.csproj" />
    <ProjectReference Include="..\DAL\DAL.csproj" />
    <ProjectReference Include="..\Seguridad\Seguridad.csproj" />
  </ItemGroup>
</Project>
