<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AlmonedaNacional.GUI</RootNamespace>
    <AssemblyName>AlmonedaNacional.GUI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlmonedaNacional.Interfaces\AlmonedaNacional.Interfaces.csproj" />
    <ProjectReference Include="..\AlmonedaNacional.BE\AlmonedaNacional.BE.csproj" />
    <ProjectReference Include="..\AlmonedaNacional.Servicios\AlmonedaNacional.Servicios.csproj" />
    <ProjectReference Include="..\AlmonedaNacional.DAL\AlmonedaNacional.DAL.csproj" />
    <ProjectReference Include="..\AlmonedaNacional.BLL\AlmonedaNacional.BLL.csproj" />
  </ItemGroup>
</Project>
