<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Servicios</RootNamespace>
    <AssemblyName>Servicios</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\BE\BE.csproj" />
  </ItemGroup>
</Project>
